name: NDK build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**.yml"
      - "!.github/workflows/build-ndk.yml"
      - "**.json"
      - "!qpm.json"
      - "!mod.template.json"
      - "**.txt"
      - "!CMakeLists.txt"
      - "**.ps1"
      - "!build.ps1"
      - "!createqmod.ps1"
      - "**.md"
      - ".gitignore"
  pull_request:
    branches:
      - master

env:
  module_id: mpchat
  qmodName: MultiplayerChat

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - uses: actions/checkout@v4
        name: Checkout
        with:
          submodules: true
          lfs: true

      - uses: seanmiddleditch/gha-setup-ninja@v5

      #- name: Get Version
      #  shell: pwsh
      #  run: |
      #    $branchParts = '${{ github.ref_name }}'.Split('/'); $branchMain = $branchParts[0]; if ($branchParts[0] -match "^\d+$") { $branchMain = 'pr'; $branchSub = "$($branchParts[0])." } elseif ($branchParts.Length -eq 2) { $branchSub = "$($branchParts[1].Replace('.', '-'))." }; echo "version=$((Get-Content ./qpm.shared.json -Raw | ConvertFrom-Json).config.info.version.Replace('+', '-').Split('-')[0])-$($branchMain).${{ github.run_number }}+$($branchSub)ra${{ github.run_attempt }}.$($env:GITHUB_SHA.Substring(0, 7))" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      #    $branchParts = '${{ github.ref_name }}'.Split('/'); $branchMain = $branchParts[0]; if ($branchParts[0] -match "^\d+$") { $branchMain = 'pr'; $branchSub = "$($branchParts[0])." } elseif ($branchParts.Length -eq 2) { $branchSub = "$($branchParts[1].Replace('.', '-'))." }; echo "qmodversion=$((Get-Content ./qpm.shared.json -Raw | ConvertFrom-Json).config.info.version.Replace('+', '-').Split('-')[0])+$($branchMain).$($branchSub)r${{ github.run_number }}a${{ github.run_attempt }}.$($env:GITHUB_SHA.Substring(0, 7))" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      #- name: Get BSVersion
      #  shell: pwsh
      #  run: |
      #     echo "BSVersion=$((Get-Content ./mod.template.json -Raw | ConvertFrom-Json).packageVersion)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Get QPM
        uses: Fernthedev/qpm-action@v1
        with:
          resolve_ndk: true
          #required
          workflow_token: ${{secrets.GITHUB_TOKEN}}
          restore: true # will run restore on download
          cache: true #will cache dependencies
          #version: '${{ env.version }}'
          #qpm_qmod: '${{ env.module_id }}_${{ env.qmodversion }}.qmod'

      - name: QPM Collapse
        run: |
          qpm collapse

      - name: List Post Restore
        run: |
          echo includes:
          ls -la ${GITHUB_WORKSPACE}/extern/includes
          echo libs:
          ls -la ${GITHUB_WORKSPACE}/extern/libs
          echo cache:
          ls -la $HOME/.local/share/QPM-RS/cache

      - name: Build & Create Qmod
        run: |
          cd ${GITHUB_WORKSPACE}
          qpm s qmod

      - name: Get Library Name
        id: libname
        run: |
          cd ./build/
          pattern="lib${module_id}*.so"
          files=( $pattern )
          echo ::set-output name=NAME::"${files[0]}"

      - name: Upload release artifact
        if: "${{ env.WEBHOOK != '' }}"
        uses: tsickert/discord-webhook@v3.2.0
        with:
          webhook-url: ${{ env.WEBHOOK }}
          content: "${{ env.CI_SHA_SHORT }} - `${{ github.event.head_commit.message }}`"
          username: "${{ github.repository }}"
          avatar-url: "http://github.com/${{ env.CI_ACTOR }}.png"
          filename: ./build/${{ steps.libname.outputs.NAME }}

      - name: Upload debug artifact
        if: "${{ env.WEBHOOK != '' }}"
        uses: tsickert/discord-webhook@v3.2.0
        with:
          webhook-url: ${{ env.WEBHOOK }}
          username: "${{ github.repository }}"
          avatar-url: "http://github.com/${{ env.CI_ACTOR }}.png"
          filename: ./build/debug/${{ steps.libname.outputs.NAME }}

      - name: Upload qmod
        if: "${{ env.WEBHOOK != '' }}"
        uses: tsickert/discord-webhook@v3.2.0
        with:
          webhook-url: ${{ env.WEBHOOK }}
          username: "${{ github.repository }}"
          avatar-url: "http://github.com/${{ env.CI_ACTOR }}.png"
          filename: ./${{ env.qmodName }}.qmod
